name: Telegram Business Bot

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  # Добавляем перезапуск по расписанию (каждые 5 часов)
  schedule:
    - cron: '0 */5 * * *'

jobs:
  run-bot:
    runs-on: ubuntu-latest
    # Жестко говорим гасить таску чуть раньше 6 часов, чтобы гитхаб не выдавал ошибку
    timeout-minutes: 340 
    
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        
    - name: Install dependencies
      run: npm install
      
    - name: Run Autoreply Bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        TARGET_USER_ID: ${{ secrets.TARGET_USER_ID }}
      run: node index.js
